### ISSUE TITLE
As Head Researcher, I need a mandatory consent form to be completed before participants complete the questionnaire so that they are fully informed of what is expected of them. 

### ISSUE THREAD

**Issue by BruceAlanMiller** [jordankeiller/AC31007-Coursework-Team-2#1]
# 2 story points.

## Tasks
- [x] Create a page allowing the user to consent using a check box
- [x] Redirect to the questionnaire if button pressed

**Comment by BruceAlanMiller** [comment]
- [ ] create a page with the consent stuff and confirm button
- [ ] It then redirect to the questionnaire if button pressed (maybe can be done for bootstrap or java).

**Comment by MikolajOlejnik** [comment]
Completed.
