### ISSUE TITLE
As Head Researcher, I need to be able to view individual responses to the questionnaire, so I can examine one response at a time

### ISSUE THREAD

**Issue by BruceAlanMiller** [jordankeiller/AC31007-Coursework-Team-2#34]
# 2 story points

## Tasks
- [x] Create a procedure which fetches a given participant's answers to a selected questionnaire
- [x] Questions and answers are displayed in a readable format

**Comment by BruceAlanMiller** [comment]
- [ ] Grab the questions from a participant’s response
- [ ] And the answers from a participant’s response

**Comment by MikolajOlejnik** [comment]
Completed.
