### ISSUE TITLE
As a Principal Researcher, I should be able to view the results of my experiments so that I can check the data received from those experiments.

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#59]
# 5 story points.

## Tasks
- [x] Create A view
- [x] Display all the questionnaires which belong to the researcher
- [x] Creating a stored procedure which returns all the questionnaires which belongs to a particular researcher
- [x] Researcher can see the results of their own experiment

**Comment by BruceAlanMiller** [comment]
- [ ] Head Researcher can access their experiments
- [ ] Head Researcher can allocate access to individual experiments

**Comment by MikolajOlejnik** [comment]
Completed.
