### ISSUE TITLE
As a Head Researcher, I should have the ability to make a new questionnaires from the front-end so that I can gather both qualitative and quantative data

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#69]
Split into smaller user stories.
#94 and #95

# 18 story points.

## Tasks
- [x] The ability to phrase questions for the participant to answer
- [x] The ability to add radio buttons.
- [x] The ability to add numbers and text
- [x] The ability to choose from a list of answers
- [x] The ability to choose multiple answers from a list
- [x] The questions and options appear as expected

**Comment by BruceAlanMiller** [comment]
- [ ] The ability to phrase questions for the participant to answer

- [ ] The ability to add radio buttons.
- [ ] the ability to add numbers and text
- [ ] the ability to choose form a list of answers
- [ ] the ability to choose multiple answers from a list

**Comment by jordankeiller** [comment]
Split into smaller user stories.

#94 and #95
