### ISSUE TITLE
As a Head Researcher, I need to be able to export the data as a CSV file so that I can store the results locally on my computer. 

### ISSUE THREAD

**Issue by BruceAlanMiller** [jordankeiller/AC31007-Coursework-Team-2#8]
# 2 story points.

## Tasks
- [x] Create an export button
- [x] Export button exports questionnaire questions and responses from the database
- [x] Exported data can be read in a CSV format

**Comment by BruceAlanMiller** [comment]
3 story points

**Comment by BruceAlanMiller** [comment]
- [ ] create an export button
- [ ] export button exports data

**Comment by MikolajOlejnik** [comment]
Completed.
