### ISSUE TITLE
As a Lab Manager/Head Researcher, I should be able to view all experiments so that I can analyse all of the data.

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#80]
# 1 story point.

## Tasks
- [x] Create a DB View to show responses for specified questionnaire.
- [x] Lab Manager/Head Researchercan select from a list of all experiments.
- [x] Lab Manager/Head Researcher can view a specific experiment.

**Comment by BruceAlanMiller** [comment]
- [ ] Head Researcher can open an experiment
- [ ] Head Researcher can open all experiments

**Comment by MikolajOlejnik** [comment]
Finished.
