### ISSUE TITLE
As a Lab Manager/Head Researcher, I need the ability to change users details in a system so that I can change login information if they get locked out.

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#81]
# 6 story points.

## Tasks
- [x]  Ability to add new logins to the database
- [x] Ability to add researchers to the database
- [x] Ability to delete researchers from the database
- [x] Ability change passwords of accounts stored in the database
- [x] Ability to change researcher's details in the database
- [x] An front-end interface that allows the above to completed without having to access the backend.
- [x] Show link to the manage logins page on dashboard.
- [x] Only allow access to lab manager.

**Comment by MikolajOlejnik** [comment]
Completed.
