### ISSUE TITLE
As a Lab Manager/Head Researcher, I need the ability to change permissions of users in the system, so I can manage access to experiments.

### ISSUE THREAD

**Issue by BruceAlanMiller** [jordankeiller/AC31007-Coursework-Team-2#82]
# 3 Story Points.

## Tasks
- [x] Lab Manager can alter permissions for co-researchers
- [x] Co-researchers can only access permitted pages
- [x] A front-end interface that allows the above functionality to be completed without having to access the backend.
- [x] Show link to manage researchers page on dashboard.
- [x] Only allow access to lab manager.

**Comment by BruceAlanMiller** [comment]
- [ ] Lab Manager can alter permissions for co-researchers
- [ ] co-researchers can only access permitted pages

**Comment by MikolajOlejnik** [comment]
Completed.
