### ISSUE TITLE
As a Head Researcher I would like to create a questionnaire with open answered questions so that I can gather qualitative data.

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#94]
# 6 story points.

## Tasks
- [x] A researcher is able to create a questionnaire
- [x] Questionnaires can be created with custom titles
- [x] The ability to create a question in which the user provides an open answer to with a text box
- [x] The questions and options appear as expected

 This question will have no input validation as to what can be entered, barring a 5000 character limit for logistic reasons.

### Bug Fixing
- [x] Fix restricting escaping unknown characters.

**Comment by MikolajOlejnik** [comment]
Completed.
