### ISSUE TITLE
As a Head Researcher I would like to create a questionnaire with questions with fixed choice answers so that I can gather quantitative data.

### ISSUE THREAD

**Issue by MikolajOlejnik** [jordankeiller/AC31007-Coursework-Team-2#95]
# 12 story points.

## Tasks
- [x] A researcher is able to create a questionnaire
- [x] Questionnaires can be created with custom titles
- [x] The ability to create a question in which the user ticks from one of the provided options
- [x] The ability to create a question in which the user ticks from multiple of the provided options
- [x] The ability for the creator to specify the options
- [x] Validation to ensure that the user cannot enter duplicate options
- [x] The questions and options appear as expected

### Bug Fixing
- [x] Fix restricting duplicates.
- [x] Fix restricting escaping unknown characters.

**Comment by MikolajOlejnik** [comment]
Completed.
